[theme]
# Color primario institucional (puedes usar el azul del gobierno mexicano)
primaryColor = "#005DAA"  # Azul oficial más oscuro para mejor contraste

# Color de fondo principal (evita negro puro)
backgroundColor = "#F8F9FA"  # Gris muy claro casi blanco

# Color secundario (púrpura institucional modificado)
secondaryBackgroundColor = "#4B2E83"  # Púrpura más profesional

# Color de texto principal (oscuro para mejor legibilidad)
textColor = "#212529"  # Casi negro para máximo contraste

# Color para texto en widgets/interactivos
widgetTextColor = "#FFFFFF"  # Blanco para texto sobre botones

# Fuente profesional
font = "sans serif"

[server]
# Configuración adicional para mejorar rendimiento
maxUploadSize = 200
maxMessageSize = 200
